### ISSUE TITLE
The population passed to callbacks is not human-readable.

### ISSUE THREAD

**Issue by alenl** [framp/timetabling-solver#5]
Hi @framp , thanks for building this great library!

I was playing around a bit and I found it is hard to debug the results since the population passed to callbacks (meta.pop member) is untabled. I propose a change that adds one more member (meta.popTables) where each entity is in form of a timetable.  It's a very simple change and I've tested it in alenl/timetabling-solver@f970379c1f580490b10263e8548eabc4c0b7e2a8 . Would you take a PR on it? If you are interested, I'll prepare it.

**Comment by framp** [comment]
Hi @alenl, glad you're liking the library!

I think it can work out, if it's behind a `debug` flag: some of the places where this function is being used are already quite slow and I wouldn't want to add another `bookables * populationElements` loop on top of it

**Comment by alenl** [comment]
Sure thing, I'll add that and make a PR.
Are you interested in other PRs?

**Comment by framp** [comment]
Really appreciated!

There are a couple optimisation/improvements here:
https://github.com/framp/timetabling-solver/issues/1

Also open to ideas and to discuss what more can we add / improve
(the original idea was to provide solvers for other timetabling problems as well, not only mininum collisions but I never had the actual need for it)
